# Generated by Django 3.2.9 on 2021-11-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publications',
            new_name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='are_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='reader',
            field=models.ManyToManyField(to='myapp.Reader'),
        ),
    ]
