# Generated by Django 3.2.9 on 2021-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211119_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_of_public',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
