# Generated by Django 3.2.9 on 2021-11-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211120_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
